"""Medical AI Clinical Platform - FastAPI application entry point.

Lifespan:
  On startup: initialise the audit DB and pre-load the ML model so the
  first inference request is not penalised by the ~2s model load time.
  On shutdown: nothing to clean up (SQLite and torch have no explicit teardown).

Endpoints mounted:
  POST /auth/token          - obtain JWT
  POST /infer/              - upload DICOM, run inference, write FHIR report
  GET  /fhir/patient/{id}   - read a FHIR Patient
  GET  /audit/              - list recent audit events
  GET  /audit/verify        - verify hash chain integrity
  GET  /health              - liveness probe (no auth)
  GET  /docs                - Swagger UI (auto-generated by FastAPI)
"""

from __future__ import annotations

from collections.abc import AsyncIterator
from contextlib import asynccontextmanager

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from api.core.config import get_settings
from api.routers import audit, auth, fhir, inference
from compliance.audit import AuditEventType, append_event, initialize_db
from ml.inference import load_model


@asynccontextmanager
async def lifespan(app: FastAPI) -> AsyncIterator[None]:
    """FastAPI lifespan context manager.

    Runs startup logic before yielding, shutdown logic after.
    Using lifespan (not deprecated on_event) is the FastAPI 0.93+ pattern.
    """
    settings = get_settings()

    # Startup
    initialize_db(settings.audit_db_path)
    append_event(
        AuditEventType.SYSTEM_START,
        actor="system",
        event_data={"app_version": settings.app_version},
        db_path=settings.audit_db_path,
    )
    load_model()  # Pre-warm — blocks startup for ~2s, saves 2s on first request

    yield  # Application runs here

    # Shutdown (nothing required for SQLite / torch)


def create_app() -> FastAPI:
    """Application factory — returns a configured FastAPI instance."""
    settings = get_settings()

    app = FastAPI(
        title=settings.app_name,
        version=settings.app_version,
        description=(
            "DICOM-native medical AI inference platform with HL7 FHIR R4 integration "
            "and FDA-aligned audit controls. Portfolio demonstration — not for clinical use."
        ),
        lifespan=lifespan,
        docs_url="/docs",
        redoc_url="/redoc",
    )

    # CORS — allow Streamlit UI to call the API
    app.add_middleware(
        CORSMiddleware,
        allow_origins=settings.allowed_origins,
        allow_credentials=True,
        allow_methods=["*"],
        allow_headers=["*"],
    )

    # Routers
    app.include_router(auth.router)
    app.include_router(inference.router)
    app.include_router(fhir.router)
    app.include_router(audit.router)

    @app.get("/health", tags=["system"])
    async def health() -> dict:
        """Liveness probe — returns 200 if the API is running."""
        return {"status": "ok", "version": settings.app_version}

    return app


app = create_app()
